name: Oselvar GitHub Metrics

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '43 * * * *'

jobs:
  update-oselvar-csv:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Update Oselvar CSV
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN || secrets.GITHUB_TOKEN }} 
      run: ./update.sh
    - name: Commit and push if it changed
      run: |-
        git config user.name "Oselvar Bot"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
